apiVersion: v1
kind: Pod
metadata:
  annotations:
    tailscale-sidecar/login-server: "foo.com"
    tailscale-sidecar/secret-name: "tailscale-auth"
  name: lifespan-seven
  namespace: apps
spec:
  containers:
    - args:
        - sleep
        - "3600"
      image: busybox
      name: lifespan-seven
  restartPolicy: Always
