---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tailscale-sidecar-webhook
  name: tailscale-sidecar-webhook
  namespace: test
spec:
  type: ClusterIP
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: tailscale-sidecar-webhook
