apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tailscale-sidecar-webhook
  name: tailscale-sidecar-webhook
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale-sidecar-webhook
  template:
    metadata:
      labels:
        app: tailscale-sidecar-webhook
    spec:
      tolerations:
        - key: tailscale-sidecar-webhook
          operator: Exists
          effect: NoSchedule
      containers:
        - image: samlockart/tailscale-sidecar-webhook:latest
          imagePullPolicy: Always
          name: injector
          env:
            - name: TLS
              value: "true"
            - name: LOG_LEVEL
              value: "trace"
            - name: LOG_JSON
              value: "false"
          volumeMounts:
            - name: tls
              mountPath: "/etc/admission-webhook/tls"
              readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: tailscale-sidecar-webhook-tls
