---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tailscale-sidecar-injector
  name: tailscale-sidecar-injector-webhook
  namespace: test
spec:
  type: NodePort
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
      nodePort: 30100
  selector:
    app: tailscale-sidecar-injector
