kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: docker.io/kindest/node:v1.31.4
    extraPortMappings:
      - containerPort: 30100
        hostPort: 8443
        listenAddress: "0.0.0.0"
        protocol: TCP
